### ISSUE TITLE
I would like to remove lab.deleted in the database

### ISSUE THREAD

**Issue by davidjhp** [Clinios/clinios#239]
Patient card Documents
I would like to remove lab.deleted from the database.
So in the frontend lets replace lab.deleted=True with lab.status=D (Declined/Deleted)

**Comment by arslansajid** [comment]
Fixed SQL for status=D

**Comment by davidjhp** [comment]
I clicked the trash can icon, but the row still appears.  After being deleted it should only appear on the Deleted tab.

**Comment by arslansajid** [comment]
I have fixed it in a way that deleted records will only show on the deleted tab, also we will not show the trash icon when the Deleted tab is selected.
